services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    hostname: pihole
    ports:
      - "100.101.135.109:53:53/tcp"
      - "100.101.135.109:53:53/udp"
      - "8080:80/tcp"
    env_file:
      - .env
    environment:
      TZ: "America/New_York"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_misc_etc_dnsmasq_d: "true"
    volumes:
      - /srv/appdata/pihole/etc-pihole:/etc/pihole
      - ./config/adlists.list:/etc/pihole/adlists.list:ro
      - ./config/dnsmasq.d:/etc/dnsmasq.d:ro
